### ISSUE TITLE
NMS CUDA kernel fails when it's running on multiple processes and on different GPUs.

### ISSUE THREAD

**Issue by ljaljushkin** [openvinotoolkit/nncf_pytorch#177]
NMS CUDA kernel fails when it's running on multiple processes and different GPU (even without wrapping by DistributedDataParallel and dist.init_process_group)
```
RuntimeError: cuda runtime error (700) : an illegal memory access was encountered at line:
```
```
THCudaCheck(cudaMemcpy(&mask_host[0],
                    mask_dev,
                    sizeof(unsigned long long) * boxes_num * col_blocks,
                    cudaMemcpyDeviceToHost));
```
The same error occurs in multi process DistributedDataParallel mode on multiple GPU when the kernel is running after dist.init_process_group and before wrapping by DistributedDataParallel.

It's OK in a single GPU mode and when it's running from a single process on multiple GPU in DataParallel mode.

The workaround is to call the kernel after wrapping by DistributedDataParallel. But this kernel can be called on the creation of the compressed model which can happen before the wrapping by DistributedDataParallel only. This is where this issue comes from. I wanted to run create_compressed_model for SSD_VGG model in evaluation mode. This mode calls NMS and fails with the mentioned error. 

Compression models in the evaluation may reduce training time by not quantizing auxiliary training branches and prevent errors with corrupting BatchNorm statistics on calling dummy_forward with random inputs for the model in training mode.

@alexsu52 @vshampor @vanyalzr @AlexKoff88

**Comment by vshampor** [comment]
The issue seems to be known (since we did not implement the NMS kernel from scratch but used a pre-made one instead):
https://github.com/facebookresearch/maskrcnn-benchmark/issues/74

**Comment by ljaljushkin** [comment]
The issue was in the NMS kernel - it allocates memory on the default device. Solved by setting the CUDA device before model compression for DDP (#172)
